# Configuración de LSPs
# ~/.config/helix/languages.toml
#
# ❯ Lenguajes
# HTML
[[language]]
name = "html"
language-servers = ["superhtml"]
auto-format = true

# CSS
[[language]]
name = "css"
auto-format = true

# Rust
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

# Astro
[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
roots = ["package.json", "astro.config.mjs"]
formatter = { command = "prettier", args = ["--parser", "astro"] }
auto-format = true
language-servers = ["astro-ls"]

# Python
[[language]]
name = "python"
language-servers = ["ty", "ruff"]
auto-format = true

# JavaScript
[[language]]
name = "javascript"
language-servers = [{ name = "typescript-language-server" }, "oxlint", "oxfmt"]
auto-format = true

# JSX
[[language]]
name = "jsx"
language-servers = [{ name = "typescript-language-server" }, "oxlint", "oxfmt"]
auto-format = true

# TypeScript
[[language]]
name = "typescript"
language-servers = [{ name = "typescript-language-server" }, "oxlint", "oxfmt"]
auto-format = true

# TSX
[[language]]
name = "tsx"
language-servers = [{ name = "typescript-language-server" }, "oxlint", "oxfmt"]
auto-format = true

# JSON
[[language]]
name = "json"
auto-format = true

# TOML
[[language]]
name = "toml"
language-servers = ["tombi"]
auto-format = true

# Markdown
[[language]]
name = "markdown"
language-servers = ["marksman", "oxfmt"]
auto-format = true

# - - - - - - - - - - - - - - - - -

# ❯ LSPs
[language-server.superhtml]
command = "superhtml"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
cachePriming = { enable = false }
cargo = { check = { extraArgs = ["-j", "2"] } }
diagnostics = { disabled = ["unresolved-proc-macro"] }

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/home/josel/.local/share/pnpm/global/5/node_modules/typescript/lib" }, environment = "node" }

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config = { provideFormatter = false, publishDiagnostics = false }

[language-server.oxlint]
command = "oxlint"
args = ["--lsp"]
config = { run = "onType" }

[language-server.oxfmt]
command = "oxfmt"
args = ["--lsp"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ty.config]
inlayHints.callArgumentNames = false
experimental.rename = true
experimental.autoImport = true

[language-server.ruff]
command = "ruff"
args = ["server"]
